### ISSUE TITLE
SF to event mesh communication

### ISSUE THREAD

**Issue by MartinStenzig** [SAP-archive/cloud-sf-extension-cap-sample#26]
In your architecture diagram I see that you somehow are using an eventing in SF to push into event mesh. When I tried to set that up in our environment I could not get it to work as (standard) event mesh is expecting an additional header and SF does not seem to have the capability to send it. I needed to build a CAP based proxy to work around it.

**Comment by navinkrishnan** [comment]
Hello @MartinStenzig 
setting headers are possible. You may check [Configure events in SAP SuccessFactors system](https://github.com/SAP-samples/cloud-sf-extension-cap-sample/blob/mission/mission/sf-configuration/README.md) chapter.

Regards,
Navin

**Comment by MartinStenzig** [comment]
Great, thx!!!
